name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Eternity
      run: dotnet nuget push **/*.nupkg -k ${NUGET_TOKEN} 
      env:
         NUGET_TOKEN: ${{secrets.PUBLIC_NUGET_TOKEN}}

    - name: Publish Eternity Proget
      run: dotnet nuget push **/*.nupkg -k ${NUGET_KEY} -s ${NUGET_SOURCE}
      env:
         NUGET_SOURCE: ${{secrets.PROGET_NUGET}}
         NUGET_KEY: ${{secrets.PROGET_NUGET_TOKEN}}  
