name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack
    - name: publish on version change
      id: Publish_Eternity
      uses: rohith/publish-nuget@v2
      with:
          PROJECT_FILE_PATH: NeuroSpeech.Eternity/NeuroSpeech.Eternity.csproj
          VERSION_STATIC: 1.4.0
          NUGET_KEY: ${{secrets.PUBLIC_NUGET_TOKEN}}
    - name: publish on version change
      id: Publish_EternityAzureStorage
      uses: rohith/publish-nuget@v2
      with:
          PROJECT_FILE_PATH: NeuroSpeech.Eternity.AzureStorage/NeuroSpeech.Eternity.AzureStorage.csproj
          VERSION_STATIC: 1.4.0
          NUGET_KEY: ${{secrets.PUBLIC_NUGET_TOKEN}}

    - name: publish on version change
      id: Publish_EternityMocks
      uses: rohith/publish-nuget@v2
      with:
          PROJECT_FILE_PATH: NeuroSpeech.Eternity.Mocks/NeuroSpeech.Eternity.Mocks.csproj
          VERSION_STATIC: 1.4.0
          NUGET_KEY: ${{secrets.PUBLIC_NUGET_TOKEN}}          
    
